# Generated by Django 5.2.15 on 2026-07-16 07:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kyc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='kyc.kycsubmission')),
                ('verifier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='completed_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-verified_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockchainRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ipfs_cid', models.CharField(max_length=255)),
                ('data_hash', models.CharField(max_length=66)),
                ('transaction_hash', models.CharField(max_length=66, unique=True)),
                ('block_number', models.BigIntegerField()),
                ('kyc_version', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_record', to='verification.verification')),
            ],
            options={
                'ordering': ['-created_at', '-kyc_version'],
                'indexes': [models.Index(fields=['kyc_version'], name='verificatio_kyc_ver_49c14d_idx')],
            },
        ),
    ]
