# Generated by Django 5.2.15 on 2026-07-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchainrecord',
            name='block_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blockchainrecord',
            name='transaction_hash',
            field=models.CharField(blank=True, max_length=66, null=True, unique=True),
        ),
    ]
