# Generated by Django 5.2.15 on 2026-07-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('VERIFIER', 'Verifier'), ('BANK', 'Bank'), ('USER', 'User')], default='USER', max_length=20),
        ),
    ]
