# Generated by Django 5.2.15 on 2026-07-16 07:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainAnchor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('network', models.CharField(choices=[('ETHEREUM', 'Ethereum'), ('POLYGON', 'Polygon'), ('LOCAL', 'Local Testnet')], default='LOCAL', max_length=20)),
                ('contract_address', models.CharField(blank=True, max_length=42)),
                ('ipfs_cid', models.CharField(max_length=100)),
                ('data_hash', models.CharField(max_length=64)),
                ('salt', models.CharField(max_length=32)),
                ('tx_hash', models.CharField(blank=True, max_length=66)),
                ('block_number', models.PositiveBigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('anchored_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-anchored_at'],
            },
        ),
    ]
