# Generated by Django 5.2.15 on 2026-07-16 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blockchain', '0001_initial'),
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchainanchor',
            name='kyc_submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_anchor', to='kyc.kycsubmission'),
        ),
    ]
