# Generated by Django 5.2.15 on 2026-07-16 07:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_code', models.CharField(max_length=20, unique=True)),
                ('swift_code', models.CharField(blank=True, max_length=11)),
                ('license_number', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('wallet_address', models.CharField(blank=True, db_index=True, max_length=42, null=True, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank', to='organization.organization')),
            ],
            options={
                'ordering': ['bank_code'],
            },
        ),
    ]
