# Generated by Django 5.2.15 on 2026-07-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='wallet_address',
            field=models.CharField(blank=True, db_index=True, max_length=42, null=True, unique=True),
        ),
    ]
