# Generated by Django 5.2.15 on 2026-07-16 07:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KYCDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('CITIZENSHIP', 'Citizenship'), ('DRIVING_LICENSE', 'Driving Licence'), ('NATIONAL_ID', 'National ID'), ('SELFIE', 'Selfie')], max_length=30)),
                ('file', models.FileField(upload_to='kyc_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'KYC Document',
                'verbose_name_plural': 'KYC Documents',
                'ordering': ['document_type'],
            },
        ),
        migrations.CreateModel(
            name='KYCSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('country', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('document_number', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-version', '-created_at'],
            },
        ),
    ]
