# Generated by Django 5.2.15 on 2026-07-16 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kyc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kycsubmission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='kyc.kycsubmission'),
        ),
        migrations.AddConstraint(
            model_name='kycsubmission',
            constraint=models.UniqueConstraint(fields=('user', 'version'), name='unique_user_version'),
        ),
        migrations.AddConstraint(
            model_name='kycdocument',
            constraint=models.UniqueConstraint(fields=('submission', 'document_type'), name='unique_document_per_submission'),
        ),
    ]
