# Generated by Django 5.2.15 on 2026-07-03 11:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kyc', '0002_delete_kycprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('country', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=20)),
                ('document_type', models.CharField(choices=[('CITIZENSHIP', 'Citizenship'), ('PASSPORT', 'Passport'), ('NATIONAL_ID', 'National ID'), ('DRIVING_LICENSE', 'Driving License')], max_length=30)),
                ('document_number', models.CharField(max_length=100)),
                ('document_front_encrypted', models.BinaryField()),
                ('document_back_encrypted', models.BinaryField(blank=True, null=True)),
                ('selfie_encrypted', models.BinaryField()),
                ('encrypted_dek', models.TextField()),
                ('document_front_hash', models.CharField(blank=True, max_length=64)),
                ('document_back_hash', models.CharField(blank=True, max_length=64)),
                ('selfie_hash', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=30)),
                ('rejection_reason', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('ipfs_cid', models.CharField(blank=True, max_length=100, null=True)),
                ('data_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('salt', models.CharField(blank=True, max_length=32, null=True)),
                ('tx_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_version', to='kyc.kycsubmission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_submissions', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_kyc_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_current'], name='kyc_kycsubm_user_id_f1ad8c_idx'), models.Index(fields=['status'], name='kyc_kycsubm_status_1d4f35_idx')],
            },
        ),
    ]
